### ISSUE TITLE
GLSL and Radeon GPU Analyzer with OpenGL target causes site error to output

### ISSUE THREAD

**Issue by jgavert** [tgjones/shader-playground#61] opened 2020-01-22 12:27 UTC
Repro:
change language to GLSL
change compiler to Radeon GPU Analyzer with 2.2 version
change compilers target from Vulkan to OpenGL
wait for a second and see following Site Error on the right side.

`System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at ShaderPlayground.Core.Compilers.Rga.RgaCompiler.GetIsaBreakdownJson(String isaCsv) in C:\Code\shader-playground\src\ShaderPlayground.Core\Compilers\Rga\RgaCompiler.cs:line 217
   at ShaderPlayground.Core.Compilers.Rga.RgaCompiler.Compile(ShaderCode shaderCode, ShaderCompilerArguments arguments) in C:\Code\shader-playground\src\ShaderPlayground.Core\Compilers\Rga\RgaCompiler.cs:line 197
   at ShaderPlayground.Core.Compiler.Compile(ShaderCode shaderCode, CompilationStep[] compilationSteps) in C:\Code\shader-playground\src\ShaderPlayground.Core\Compiler.cs:line 119
   at ShaderPlayground.Web.Controllers.ApiController.Compile(ShaderCompilationRequestViewModel model) in C:\Code\shader-playground\src\ShaderPlayground.Web\Controllers\ApiController.cs:line 17`

**Comment by tgjones** [comment] 2020-02-16 09:51
Duplicate of #62.

**Closed by tgjones** 2020-02-16 09:51 UTC
